### PR TITLE
remove 5.4, upgrade to cakephp 3.6, upgrade phpunit to 5

### PR DESCRIPTION
**Pull request by styks1111**
3.6 is here with a lot of depreciation changes. Tests updated.

### CODE REVIEW

**Comment by bcrowe** [comment]
Wonderful! Any chance you're interested in getting the tests to pass on Travis again?

**Comment by styks1111** [comment]
@bcrowe - Fixed the phpunit version referenced in the tests

**Comment by bcrowe** [comment]
You're the best! Thank you!

**Comment by bcrowe** [comment]
Tagged 1.2.0. https://github.com/bcrowe/cakephp-api-pagination/releases/tag/1.2.0

**Pull request merged**
