### PR TITLE
Cakephp 4.X changes

### PR DESCRIPTION
**Pull request by Devin345458**
See https://book.cakephp.org/4/en/appendices/4-0-migration-guide.html#id1

### CODE REVIEW

**Comment by bcrowe** [comment]
Covered in https://github.com/bcrowe/cakephp-api-pagination/pull/4 unless you think this may be cleaner?

**Comment by bcrowe** [comment]
@Devin345458 By the way, extremely sorry for the big delay. I've gotten #4 merged, and tagged with a 2.0.0 release. I've moved the CakePHP 3.x code into a 1.x branch. CakePHP 4.x code will live in master and be 2.x.x tags. Thanks for the help! And let me know if you think this PR is still relevant/an improvement on how #4 approached getting the attributes.

**Comment by Devin345458** [comment]
@bcrowe No, I think the way you did it was fine. I will mention that they are getting rid of the [_serialize] array auto serialization soon according to the docs. It should be set via $this->viewBuilder()->setOption('serialize', ['recipe']); now. You can read about it here https://book.cakephp.org/4/en/appendices/4-0-migration-guide.html#view

**Comment by jfalbel** [comment]
@bcrowe can u please review @Devin345458 answer? 

> @bcrowe No, I think the way you did it was fine. I will mention that they are getting rid of the [_serialize] array auto serialization soon according to the docs. It should be set via $this->viewBuilder()->setOption('serialize', ['recipe']); now. You can read about it here https://book.cakephp.org/4/en/appendices/4-0-migration-guide.html#view

**Comment by bcrowe** [comment]
Closed via #6

**Pull request closed without merging**
